package de.fhe.fhemobile.api;

import android.util.Log;

import org.openapitools.client.ApiClient;
import org.openapitools.client.api.StudiengangApi;
import org.openapitools.client.model.Studiengang;
import org.openapitools.client.model.StudiengangByIdReponse;
import org.openapitools.client.model.StudiengangReponse;

import java.util.List;

import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

/**
 * This class wraps methods generated by openApiGenerate
 * to call study program related API endpoints.
 */
public class MosesStudiengangApi {
    private final StudiengangApi studiengangApiService;

    public MosesStudiengangApi(ApiClient apiClient) {
        this.studiengangApiService = apiClient.createService(StudiengangApi.class);
    }
    /**
     * Get all study programs. You can query a specific page by querying by providing pageNumber
     * or to get all entries without pagination set the pageSize to a large number.
     *
     * @param pageNumber
     * @param pageSize
     * @param _Callback
     */
    public void studiengangGetAll(
            Integer pageNumber,
            Integer pageSize,
            Callback<StudiengangReponse> _Callback
    ) {
        studiengangApiService
                .v1StudiengangGetAll(pageNumber, pageSize)
                .enqueue(_Callback);
    }

    public void studiengangGetById(Integer id) {
        studiengangApiService
                .v1StudiengangidGetById(id)
                .enqueue(studiengangByIdReponseCallback);
    }

    public Callback<StudiengangByIdReponse> studiengangByIdReponseCallback =
            new Callback<StudiengangByIdReponse>() {
                @Override
                public void onResponse(
                        Call<StudiengangByIdReponse> call,
                        Response<StudiengangByIdReponse> response
                ) {
                    if (response.isSuccessful()) {
                        StudiengangByIdReponse studiengangReponse = response.body();

                        List<Studiengang> studiengangList = null;
                        Studiengang studiengang = null;

                        if (studiengangReponse != null) {
                            studiengangList = studiengangReponse.getData();
                            if (studiengangList != null) {
                                studiengang = studiengangList.get(0);
                                Log.e("calz", studiengang.getName());
                            }
                        }
                    }
                }

                @Override
                public void onFailure(
                        Call<StudiengangByIdReponse> call,
                        Throwable throwable
                ) {

                }
            };
}
